// Generates one ordinary static route per directory under `static/files/`.
//
// Why generate routes instead of using a single `[...path]` rest route: a rest
// route does not compose with this site's `paths.relative` prerendering. The
// prerenderer feeds phantom URLs back into the route and recurses, producing
// pages with ~2000-character parameters -- and hanging outright under
// `trailingSlash: 'always'`. Plain static routes are just pages, like /about,
// so none of that can happen. They also get the site's layout, styling and
// dark mode for free, which hand-written HTML would not.
//
// Output is gitignored and rebuilt by `npm run dev`, `npm run build` and
// `npm run check`.
//
// This runs once, at startup. `vite dev` will not notice documents added to or
// removed from static/files/ while it is running -- restart it to pick them up.

import fs from 'node:fs';
import path from 'node:path';
import { NAME_RULES, allDirs, collectViolations, readDir } from './file-tree.mjs';

const OUT = path.join(process.cwd(), 'src', 'routes', 'browse');

// Embedded in a <script> block, so `</script>` inside a filename would close it
// early. Escaping every `<` keeps the JSON valid and inert.
//
// Everything outside printable ASCII is escaped too. Filenames legitimately
// contain accents and CJK, but they can also carry bidirectional control
// characters (U+202E and friends) that reorder how the surrounding source is
// displayed, so a reviewer opening this file would be shown something other
// than what it says. `\uXXXX` escapes are the same string at runtime and read
// unambiguously.
//
// Note this does not silence Svelte's bidirectional_control_characters warning:
// that check inspects the decoded string value, not the source bytes, so a
// document whose name contains one still warns on every `npm run check`. It is
// a warning, not an error. `displayName` in file-tree.mjs handles the part that
// actually matters -- what the visitor sees.
const embed = (value) =>
    JSON.stringify(value).replace(
        /[<\u007f-\uffff]/g,
        (c) => `\\u${c.charCodeAt(0).toString(16).padStart(4, '0')}`
    );

// Reject unpublishable names before generating anything. Skipping them would
// mean a document silently never appears on the site, which is a worse failure
// than a build that stops and says why. Everything is reported at once so a
// rename pass can fix the lot in one go.
const violations = collectViolations();
if (violations.length > 0) {
    const line = (v) => `  static/files/${v.path}${v.kind === 'dir' ? '/' : ''}`;
    const dirs = violations.filter((v) => v.kind === 'dir');
    const files = violations.filter((v) => v.kind === 'file');
    console.error(
        `\ngen-browse: ${violations.length} name${violations.length === 1 ? '' : 's'} ` +
            `cannot be published.\n`
    );
    if (dirs.length) {
        console.error(`Folder names must start with a letter or digit and use only`);
        console.error(`${NAME_RULES.dir} --`);
        dirs.forEach((v) => console.error(line(v)));
        console.error('');
    }
    if (files.length) {
        console.error(`File names must start with a letter or digit and use only`);
        console.error(`${NAME_RULES.file} --`);
        files.forEach((v) => console.error(line(v)));
        console.error('');
    }
    console.error('Rename them and run the build again. Accents and non-Latin');
    console.error('scripts are fine; punctuation with a meaning in URLs is not.\n');
    process.exit(1);
}

fs.rmSync(OUT, { recursive: true, force: true });

// `allDirs()` is empty when static/files/ does not exist yet; the root listing
// still has to exist, or the nav link to it 404s and fails the build.
const dirs = allDirs();
if (!dirs.includes('')) dirs.unshift('');
for (const dir of dirs) {
    // Directory names that SvelteKit would read as route syntax are filtered
    // out by the walker, so every segment here is safe to use verbatim.
    const target = dir ? path.join(OUT, ...dir.split('/')) : OUT;
    fs.mkdirSync(target, { recursive: true });

    const data = { path: dir, entries: readDir(dir) ?? [] };
    fs.writeFileSync(
        path.join(target, '+page.svelte'),
        `<!-- Generated by scripts/gen-browse.mjs. Do not edit; your changes will be overwritten. -->\n` +
            `<script lang="ts">\n` +
            `    import Listing from '$lib/listing.svelte';\n` +
            `    import type { Entry } from '$lib/files';\n` +
            `    const data: { path: string; entries: Entry[] } = ${embed(data)};\n` +
            `</script>\n\n` +
            `<Listing path={data.path} entries={data.entries} />\n`
    );
}

console.log(`gen-browse: ${dirs.length} listing page${dirs.length === 1 ? '' : 's'}`);
