// Generates one ordinary static route per folder under `static/files/`, so the
// document archive gets browsable listing pages.
//
// Why generate routes rather than use a single `[...path]` rest route: a rest
// route does not compose with this site's `paths.relative` prerendering. The
// prerenderer resolves the listings' relative hrefs against the wrong base,
// feeds the resulting phantom URLs back into the route, and recurses -- emitting
// pages with ~2000-character parameters, and hanging outright under
// `trailingSlash: 'always'`. Plain static routes cannot be fed back into
// themselves, and they inherit the site layout, styling and dark mode for free.
//
// Everything it writes lives under src/routes/browse/, which is gitignored and
// deleted at the start of every run. Do not put hand-written routes there; any
// other route in src/routes/ is unaffected by this script.
//
// Runs at the start of `npm run dev`, `npm run build` and `npm run check`, once
// each time: `vite dev` will not notice documents added to or removed from
// static/files/ while it is running. Restart it to pick them up.

import fs from 'node:fs';
import path from 'node:path';
import { NAME_RULES, readTree } from './file-tree.mjs';

/** @typedef {import('./file-tree.mjs').Violation} Violation */

// Resolved from this file's location rather than process.cwd(), so the script
// behaves the same however it is invoked.
const OUT = path.join(import.meta.dirname, '..', 'src', 'routes', 'browse');

/**
 * Serialise data for embedding in a `<script>` block.
 *
 * `</script>` inside a filename would close the block early, so every `<` is
 * escaped. Everything above printable ASCII is escaped too: accents and CJK are
 * perfectly legal in a document name, and `\uXXXX` keeps the generated file
 * readable as plain ASCII without changing the string at runtime.
 *
 * @param {unknown} value
 */
const embed = (value) =>
    JSON.stringify(value).replace(
        /[<\u007f-\uffff]/g,
        (c) => `\\u${c.charCodeAt(0).toString(16).padStart(4, '0')}`
    );

const { listings, violations } = readTree();

// Refuse to publish an unusable name rather than skipping it: a document that
// silently never appears is a worse failure than a build that stops and says
// why. Everything is reported at once, so one rename pass can fix the lot.
if (violations.length > 0) {
    const nameNote =
        '  Accents and non-Latin scripts are fine; punctuation that means\n' +
        '  something in a URL is not.';

    /** @type {[Violation['kind'], string][]} */
    const groups = [
        [
            'dir',
            `Folder names must start with a letter or digit and use only\n  ${NAME_RULES.dir}\n` +
                nameNote
        ],
        [
            'file',
            `File names must start with a letter or digit and use only\n  ${NAME_RULES.file}\n` +
                nameNote
        ],
        ['symlink', 'Symlinks are not published: they can point outside the archive.'],
        [
            'long',
            'These paths are too long to survive a checkout on Windows.\n' +
                `  Keep ${NAME_RULES.long}.`
        ]
    ];

    const n = violations.length;
    console.error(`\ngen-browse: ${n} name${n === 1 ? '' : 's'} cannot be published.\n`);
    for (const [kind, explanation] of groups) {
        const group = violations.filter((v) => v.kind === kind);
        if (group.length === 0) continue;
        console.error(explanation);
        for (const v of group) {
            console.error(`    static/files/${v.path}${v.kind === 'dir' ? '/' : ''}`);
        }
        console.error('');
    }
    console.error('Rename or remove them, then run the build again.\n');
    process.exit(1);
}

fs.rmSync(OUT, { recursive: true, force: true });

for (const [dir, entries] of listings) {
    // Folder names SvelteKit would read as route syntax are rejected above, so
    // every segment here is safe to use verbatim.
    const target = dir ? path.join(OUT, ...dir.split('/')) : OUT;
    fs.mkdirSync(target, { recursive: true });
    fs.writeFileSync(
        path.join(target, '+page.svelte'),
        '<!-- Generated by scripts/gen-browse.mjs. Do not edit; it is overwritten. -->\n' +
            '<script lang="ts">\n' +
            "    import Listing from '$lib/listing.svelte';\n" +
            "    import type { Entry } from '$lib/files';\n" +
            `    const path: string = ${embed(dir)};\n` +
            `    const entries: Entry[] = ${embed(entries)};\n` +
            '</script>\n\n' +
            '<Listing {path} {entries} />\n'
    );
}

console.log(`gen-browse: ${listings.size} listing page${listings.size === 1 ? '' : 's'}`);
